name: Build and test Shopping app

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: Install NPM dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm run test:unit

            - name: display Softuni username
              run: echo ProgrammerWannaBe

    run_ui_tests:
        runs-on: ubuntu-latest
        needs: build_and_test
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: install npm dependencies
              run: npm install

            - name: install Playwright Browsers
              run: npx playwright install
            - name: Run application in background mode
              run: npm run start &
            - name: Run UI tests
              run: npm run test:ui

    deploy-production:
        runs-on: ubuntu-latest
        needs: run_ui_tests
        steps:
            - name: Deploy to production
              uses: JorgeLNJunior/render-deploy@v1.4.4
              with:
                  service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
                  api_key: ${{ secrets.MY_RENDER_API_KEY }}
                  wait_deploy: true
